# Generated by Django 3.0.6 on 2021-01-22 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=40)),
                ('customer_email', models.EmailField(max_length=254, null=True)),
                ('customer_address', models.CharField(max_length=100, null=True)),
                ('customer_phone', models.CharField(max_length=10)),
                ('customer_add', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discon_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dic_on_bill_rs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_date', models.DateTimeField(auto_now=True)),
                ('bill', models.FileField(upload_to='')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery_store_management.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bar_code', models.CharField(max_length=13)),
                ('product_name', models.CharField(max_length=100)),
                ('product_date', models.DateField(auto_now=True)),
                ('product_image', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=100)),
                ('seller_phone', models.CharField(max_length=10)),
                ('seller_email', models.EmailField(max_length=254, null=True)),
                ('seller_address', models.CharField(max_length=100, null=True)),
                ('seller_payment_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_payment_due', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Purchased_product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pproduct_name', models.CharField(max_length=100)),
                ('pproduct_Quantity', models.IntegerField()),
                ('pproduct_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pproduct_total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pproduct_purchased', models.DateField(auto_now=True)),
                ('pproduct_payment_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pproduct_payment_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery_store_management.Orders')),
            ],
        ),
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_Purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_units', models.IntegerField()),
                ('product_purchase_date', models.DateField(auto_now=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery_store_management.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery_store_management.Seller'),
        ),
    ]
