# Generated by Django 3.0.6 on 2021-01-22 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store_management', '0002_auto_20210122_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchased_product',
            name='pproduct_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery_store_management.Product'),
        ),
    ]
