# Generated by Django 3.0.6 on 2021-01-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store_management', '0004_seller_seller_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_catagories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
