# Generated by Django 3.0.6 on 2021-01-27 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store_management', '0005_product_catagories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='grocery_store_management.product_catagories'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_catagories',
            name='category_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
